variable_a = int(input('Введите переменную a: '))
variable_b = int(input('Введите переменную b: '))
variable_c = int(input('Введите переменную c: '))
variable_d = variable_a + variable_b * (variable_c / 2)
print('При переменной a равной %d \nпеременной b равной %d \nпеременной c равной \nОтвет: %d' % (variable_a, variable_d, variable_c))
